fix: l'action Update fonctionne correctement
Le problème venait des lignes en commentaire ou je "get" une person de ma db avec l'ID venant
de la route pour vérifier si une person existe avec cet ID. Cela créait une entité tracké avec
le même ID :
System.InvalidOperationException: The instance of entity type 'Person' cannot be tracked because
another instance with the key value '{Id: 4}' is already being tracked. When attaching existing entities,
ensure that only one entity instance with a given key value is attached.

Je ne comprends pas la raison de ce message d'erreur. Après avoir vérifier à plusieurs endroits
(anciens projets, cours, vidéo youtube)

Un code similaire est présent (le même dans le cas des mes anciens projets) et il ne provoque pas
d'erreur.